Javadocs for interfaces and abstract calsses
oubaydos/java-random-instances-generator pull request #28
Opened 2022-11-25 19:15 UTC by oubaydos

2022-11-25 19:58 UTC, HamzaBenyazid requested changes

2022-11-25 19:58 UTC, HamzaBenyazid commented on src/main/java/io/javarig/generator/TypeBasedGenerator.java
> + * type generator for classes that require an extra type
This is not clear 
I think better say :  type generator for classes that require the Type object that holds information about the object to generate

2022-11-25 19:58 UTC, HamzaBenyazid commented on src/main/java/io/javarig/generator/list/ListGenerator.java
> + * note: generates an ArrayList if not given otherwise
This information is not handled here. The code doesn't generate ArrayList if no implementation type was given. We did that in the TypeEnum when we gave the LIST enum ArrayListGenerator.
I find this command is confusing.

2022-11-25 19:58 UTC, HamzaBenyazid commented on src/main/java/io/javarig/generator/map/MapGenerator.java
> + * Note: generates a hashmap if not given otherwise
The same applies here

2022-11-25 20:05 UTC, HamzaBenyazid commented on src/main/java/io/javarig/generator/list/ListGenerator.java
> + * note: generates an ArrayList if not given otherwise
check **Nonlocal Information** in chapter 4 of **Clean Code** book
https://thixalongmy.haugiang.gov.vn/media/1175/clean_code.pdf

2022-12-03 22:02 UTC, mosle77 approved these changes

2022-12-03 22:04 UTC, HamzaBenyazid approved these changes

2022-12-03 22:04 UTC, merged